# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    volumes:
      # Configuration files
      - type: bind
        source: ../.env
        target: /app/.env
        read_only: true
      # Application code
      - type: bind
        source: ../api
        target: /app/api
        read_only: true
      - type: bind
        source: ../config
        target: /app/config
        read_only: true
      - type: bind
        source: ../knowledge_agents
        target: /app/knowledge_agents
        read_only: true
      - type: volume
        source: app_data
        target: /app/data
        read_only: false
      - type: bind
        source: ../tests
        target: /app/tests
        read_only: true
      # Persistent volumes
      - type: volume
        source: poetry_cache
        target: /home/nobody/.cache/pypoetry
      - type: volume
        source: app_logs
        target: /app/logs
      - type: volume
        source: app_temp
        target: /app/temp_files
    user: "nobody:nogroup"
    env_file:
      - ../.env
    environment:
      # Docker environment
      - DOCKER_ENV=true
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - FASTAPI_ENV=production
      - FASTAPI_DEBUG=false
      
      # Data management settings
      - DATA_RETENTION_DAYS=14
      - ENABLE_DATA_SCHEDULER=true
      - DATA_UPDATE_INTERVAL=3600
      - AUTO_CHECK_DATA=false
      
      # API configuration
      - API_PORT=80
      - HOST=0.0.0.0
      - API_WORKERS=4
      - LOG_LEVEL=info
      
      # Test execution control (disabled by default in production)
      # To enable integrated test and deploy workflow, uncomment the line below
      # OR use one of these commands:
      #   Linux/macOS: docker-compose -f deployment/docker-compose.yml -e RUN_TESTS_ON_STARTUP=true up -d
      #   Windows PowerShell: $env:COMPOSE_RUN_TESTS_ON_STARTUP="true"; docker-compose -f deployment/docker-compose.yml up -d
      #   Windows CMD: set COMPOSE_RUN_TESTS_ON_STARTUP=true && docker-compose -f deployment/docker-compose.yml up -d
      # - RUN_TESTS_ON_STARTUP=true
      - TEST_TYPE=all
      
      # Advanced test configuration
      # - ABORT_ON_TEST_FAILURE=false  # Set to true to abort deployment if tests fail
      # - TEST_RESULTS_DIR=/app/test_results  # Directory to store test results
      
      # System Configuration
      - TZ=UTC
      - PYTHONOPTIMIZE=2
      - PYTHONASYNCIODEBUG=0
      - PYTHONWARNINGS=ignore
    ports:
      - "80:80"
    networks:
      knowledge-net:
        aliases:
          - knowledge-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    restart: unless-stopped
    stop_grace_period: 30s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '1'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "production"
        env: "FASTAPI_ENV,DOCKER_ENV"

networks:
  knowledge-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
    labels:
      environment: production

volumes:
  poetry_cache:
    driver: local
    labels:
      environment: production
  app_data:
    driver: local
    labels:
      environment: production
  app_logs:
    driver: local
    labels:
      environment: production
  app_temp:
    driver: local
    labels:
      environment: production