# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# The version attribute is now auto-detected and the explicit declaration is obsolete
# Removed version: '3.8' to avoid warnings

services:
  test-runner:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      - TEST_MODE=true
    volumes:
      - ..:/app
    command: ["python3", "-m", "pytest"]

networks:
  test-net:
    driver: bridge
    labels:
      environment: testing

volumes:
  test_data:
    driver: local
    labels:
      environment: testing
  test_data_stratified:
    driver: local
    labels:
      environment: testing
  test_data_shared:
    driver: local
    labels:
      environment: testing
  test_logs:
    driver: local
    labels:
      environment: testing
  test_temp:
    driver: local
    labels:
      environment: testing 