# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# The version attribute is now auto-detected and the explicit declaration is obsolete
# Removed version: '3.8' to avoid warnings

services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "${API_PORT:-80}:80"
    volumes:
      - ..:/app
    environment:
      - ENVIRONMENT=docker
      - DOCKER_ENV=true
      # Explicitly unset REPLIT_ENV to prevent conflicts
      - REPLIT_ENV=
      # Add other environment variables here or use an env_file
    command: ["python3", "-m", "uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "80"]

  # Example of another service, e.g., a scheduler
  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   command: ["bash", "scripts/docker_scheduler.sh"]

volumes:
  app_data:
    driver: local
  app_logs:
    driver: local
  app_temp:
    driver: local