services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    volumes:
      - type: bind
        source: ../.env
        target: /app/.env
        read_only: true
      - type: bind
        source: ../api
        target: /app/api
        read_only: true
      - type: bind
        source: ../config
        target: /app/config
        read_only: true
      - type: bind
        source: ../knowledge_agents
        target: /app/knowledge_agents
        read_only: true
      - type: volume
        source: poetry_cache
        target: /home/nobody/.cache/pypoetry
      - type: volume
        source: app_data
        target: /app/data
      - type: volume
        source: app_logs
        target: /app/logs
      - type: volume
        source: app_temp
        target: /app/temp_files
    user: "nobody:nogroup"
    env_file:
      - ../.env
    environment:
      - DOCKER_ENV=true
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - FASTAPI_ENV=production
      - FASTAPI_DEBUG=false
      - SETUP_TIMEOUT=120
      - INIT_WAIT_TIME=300
      - API_WORKERS=4  # Set number of worker processes
      
      # API Paths
      - API_BASE_PATH=/api/v1
      - API_BASE_URL=http://localhost/api/v1
      
      # System Configuration
      - TZ=UTC
      - PYTHONOPTIMIZE=2  # Enable Python optimizations
      - PYTHONASYNCIODEBUG=0  # Disable async debug for better performance
      - PYTHONWARNINGS=ignore  # Reduce logging overhead
    ports:
      - "80:80"
    networks:
      knowledge-net:
        aliases:
          - knowledge-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    stop_grace_period: 30s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '1'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "production"
        env: "FASTAPI_ENV,DOCKER_ENV"

networks:
  knowledge-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
    labels:
      environment: production

volumes:
  poetry_cache:
    driver: local
    labels:
      environment: production
  app_data:
    driver: local
    labels:
      environment: production
  app_logs:
    driver: local
    labels:
      environment: production
  app_temp:
    driver: local
    labels:
      environment: production