query:
  description: "Tweet-optimized queries for extracting concise insights"
  example:
    - "What's the latest shift in market sentiment, and which trends are emerging in the global economy?"
    - "What's the latest development in global hotspots, and which underreported conflicts have potential for escalation?"
    - "What's the latest development in key policy initiatives, and which emerging trends in public opinion have potential for significant impact?"
    - "What's the latest development in alternative investment strategies, and which emerging trends have potential for significant growth?"
    - "What's the latest development in emerging technologies, and which underreported demographic trends have potential for significant impact?"